version: "3.3"
# Docker compose file for development
services:

  backend:
    depends_on:
      - db
    extends:
      file: docker-compose.base.yml
      service: backend
    volumes:
      - ./backend:/app
    entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload --log-level debug
    environment:
      - DEV_MODE=true
    ports:
      - 3000:80

  frontend:
    depends_on:
      - backend
    extends:
      file: docker-compose.base.yml
      service: frontend
    volumes:
      - ./frontend/src:/app/src
    entrypoint: pnpm dev
    ports:
      - 3001:3001

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - 7878:7878
