version: "3.3"
services:

  cohort-explorer-backend:
    build: ./backend
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: api.icare.137.120.31.102.nip.io
      LETSENCRYPT_HOST: api.icare.137.120.31.102.nip.io
      FRONTEND_URL: https://icare.137.120.31.102.nip.io
    volumes:
      # - /data/icare4cvd-upload:/data
      - ./data:/data
    ports:
      - 3000:80
    env_file:
      - .env

  cohort-explorer-frontend:
    build: ./frontend
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: icare.137.120.31.102.nip.io
      LETSENCRYPT_HOST: icare.137.120.31.102.nip.io
    ports:
      - 3001:3000
    volumes:
      - ./data:/data
      # - /data/icare4cvd-upload:/data
    env_file:
      - .env
