version: "3.3"
services:

  backend:
    build: ./backend
    environment:
      FRONTEND_URL: http://localhost:3001
      SPARQL_ENDPOINT: "http://db:7878"
      DATA_FOLDER: /data
    volumes:
      - ./data:/data
      - ./backend:/app
    ports:
      - 3000:80
    env_file:
      - .env
    # entrypoint: "uvicorn src.main:app --host 0.0.0.0 --port 80 --reload --log-level debug"


  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - 3001:3000
    volumes:
      - ./data:/data
      - ./frontend/src:/app/src
    env_file:
      - .env


  db:
    image: ghcr.io/oxigraph/oxigraph:latest
    volumes:
      - ./data/db:/data
    ports:
      - 7878:7878
