# Base docker-compose file used by the dev and prod environments
services:

  backend:
    build: ./backend
    environment:
      FRONTEND_URL: http://localhost:3001
      SPARQL_ENDPOINT: "http://db:7878"
      DATA_FOLDER: /data
    volumes:
      - ./data:/data
      - /data/deploy-services/cohort-explorer/cohortVarLinker/data/:/app/CohortVarLinker/data/
      - /data/deploy-services/cohort-explorer/cohortVarLinker/data/:/app/CohortVarLinker/mapping_output
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3000
    env_file:
      - .env
    volumes:
      - ./data:/data

  db:
    image: oxigraph/oxigraph:latest
    # image: oxigraph/oxigraph:0.4.0-alpha.3
    volumes:
      - ./data/db:/data
