version: "3.3"
services:

  cohort-explorer-backend:
    build: ./backend
    environment:
      FRONTEND_URL: http://localhost:3001
    volumes:
      # - /data/icare4cvd-upload:/data
      - ./data:/data
    ports:
      - 3000:80
    env_file:
      - .env

  cohort-explorer-frontend:
    build: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./data:/data
      # - /data/icare4cvd-upload:/data
    env_file:
      - .env
