class CodeGenerator:
    def __init__(self, start_value=2000000000):
        # Initialize the starting value above 2 billion to comply with OMOP standards.
        self.counters = {
            "cvd": start_value,
        }

    def generate_code_and_id(self, domain, variable_label=None, suffix=None):
        # Increment the counter for the given domain and return the unique code.
        if domain not in self.counters:
            raise ValueError(f"Invalid domain: {domain}")

        self.counters[domain] += 1
        base_code = f"icare:icv{self.counters[domain]}"
        return (
            variable_label,
            f"{base_code}_{suffix}" if suffix else base_code,
            self.counters[domain],
        )


# create list and run the code

codes_list = {
    "cvd": [
        "follow-up 30 months",
        "follow-up 42 months",
        "follow-up 48 months",
        "follow-up 3 years",
        "follow-up 54 months",
        "follow-up 60 months",
        "end of study last follow-up",
        "follow-up 66 months",
        "A lateral",
        "A right ventricular (RV)",
        "A septal",
        "E right ventricular (RV)",
        "E septal",
        "systolic septal",
        "seed oil",
    ],
}
code_output = []
# Example usage
code_gen = CodeGenerator()
for domain, labels in codes_list.items():
    for label in labels:
        code_output.append(code_gen.generate_code_and_id(domain, label))
print(code_output)

# import csv

# # Define the data to be added to the CSV file
# data = [
#     [
#         "VARIABLE NAME",
#         "VARIABLE LABEL",
#         "Domain",
#         "var",
#         "Variable Concept Code",
#         "Variable Concept OMOP ID",
#         "Additional Context Concept Label",
#         "Additional Context Concept Code",
#         "Additional Context OMOP ID",
#         "Primary to Secondary Context Relationship",
#         "Categorical Values Concept Label",
#         "Categorical Values Concept Code",
#         "Categorical Values Concept OMOP ID",
#         "Unit Concept Label",
#         "Unit Concept Code",
#         "Unit OMOP ID",
#     ],
#     [
#         "month30_a",
#         "follow-up 30 months",
#         "visit",
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month30_b",
#         "follow-up 30 month",
#         "visit",
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month30_c",
#         "follow-up month 30",
#         "visit",
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month30_d",
#         "30 month follow up",
#         "visit",
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "follow-up 30 months",
#         "icare:icv2000000001",
#         2000000001,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month42_a",
#         "follow-up 42 months",
#         "visit",
#         "follow-up 42 months",
#         "icare:icv2000000002",
#         2000000002,
#         "follow-up 42 months",
#         "icare:icv2000000002",
#         2000000002,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month42_b",
#         "follow-up month 42",
#         "visit",
#         "follow-up 42 months",
#         "icare:icv2000000002",
#         2000000002,
#         "follow-up 42 months",
#         "icare:icv2000000002",
#         2000000002,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month42_c",
#         "42 month follow-up",
#         "visit",
#         "follow-up 42 months",
#         "icare:icv2000000002",
#         2000000002,
#         "follow-up 42 months",
#         "icare:icv2000000002",
#         2000000002,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month48_a",
#         "follow-up 48 months",
#         "visit",
#         "follow-up 48 months",
#         "icare:icv2000000003",
#         2000000003,
#         "follow-up 48 months",
#         "icare:icv2000000003",
#         2000000003,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month48_b",
#         "48 month follow-up",
#         "visit",
#         "follow-up 48 months",
#         "icare:icv2000000003",
#         2000000003,
#         "follow-up 48 months",
#         "icare:icv2000000003",
#         2000000003,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month48_c",
#         "follow-up month 48",
#         "visit",
#         "follow-up 48 months",
#         "icare:icv2000000003",
#         2000000003,
#         "follow-up 48 months",
#         "icare:icv2000000003",
#         2000000003,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month3y_a",
#         "follow-up 3 years",
#         "visit",
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month3y_b",
#         "3 years follow-up",
#         "visit",
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month3y_c",
#         "3-year follow-up",
#         "visit",
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month3y_d",
#         "follow-up after 3 years",
#         "visit",
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "follow-up 3 years",
#         "icare:icv2000000004",
#         2000000004,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month54_a",
#         "follow-up 54 months",
#         "visit",
#         "follow-up 54 months",
#         "icare:icv2000000005",
#         2000000005,
#         "follow-up 54 months",
#         "icare:icv2000000005",
#         2000000005,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month54_b",
#         "54 month follow-up",
#         "visit",
#         "follow-up 54 months",
#         "icare:icv2000000005",
#         2000000005,
#         "follow-up 54 months",
#         "icare:icv2000000005",
#         2000000005,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month54_c",
#         "follow-up month 54",
#         "visit",
#         "follow-up 54 months",
#         "icare:icv2000000005",
#         2000000005,
#         "follow-up 54 months",
#         "icare:icv2000000005",
#         2000000005,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month60_a",
#         "follow-up 60 months",
#         "visit",
#         "follow-up 60 months",
#         "icare:icv2000000006",
#         2000000006,
#         "follow-up 60 months",
#         "icare:icv2000000006",
#         2000000006,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month60_b",
#         "60 month follow-up",
#         "visit",
#         "follow-up 60 months",
#         "icare:icv2000000006",
#         2000000006,
#         "follow-up 60 months",
#         "icare:icv2000000006",
#         2000000006,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month60_c",
#         "follow-up month 60",
#         "visit",
#         "follow-up 60 months",
#         "icare:icv2000000006",
#         2000000006,
#         "follow-up 60 months",
#         "icare:icv2000000006",
#         2000000006,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "monthEnd_a",
#         "end of study last follow-up",
#         "visit",
#         "end of study last follow-up",
#         "icare:icv2000000007",
#         2000000007,
#         "end of study last follow-up",
#         "icare:icv2000000007",
#         2000000007,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "monthEnd_b",
#         "final follow-up",
#         "visit",
#         "end of study last follow-up",
#         "icare:icv2000000007",
#         2000000007,
#         "end of study last follow-up",
#         "icare:icv2000000007",
#         2000000007,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "monthEnd_c",
#         "last follow-up",
#         "visit",
#         "end of study last follow-up",
#         "icare:icv2000000007",
#         2000000007,
#         "end of study last follow-up",
#         "icare:icv2000000007",
#         2000000007,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month66_a",
#         "follow-up 66 months",
#         "visit",
#         "follow-up 66 months",
#         "icare:icv2000000008",
#         2000000008,
#         "follow-up 66 months",
#         "icare:icv2000000008",
#         2000000008,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month66_b",
#         "66 month follow-up",
#         "visit",
#         "follow-up 66 months",
#         "icare:icv2000000008",
#         2000000008,
#         "follow-up 66 months",
#         "icare:icv2000000008",
#         2000000008,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "month66_c",
#         "follow-up month 66",
#         "visit",
#         "follow-up 66 months",
#         "icare:icv2000000008",
#         2000000008,
#         "follow-up 66 months",
#         "icare:icv2000000008",
#         2000000008,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "A_lateral_a",
#         "A lateral",
#         "anatomic site",
#         "A lateral",
#         "icare:icv2000000009",
#         2000000009,
#         "A lateral",
#         "icare:icv2000000009",
#         2000000009,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "A_lateral_b",
#         "Lateral A",
#         "anatomic site",
#         "A lateral",
#         "icare:icv2000000009",
#         2000000009,
#         "A lateral",
#         "icare:icv2000000009",
#         2000000009,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "A_RV_a",
#         "A right ventricular (RV)",
#         "anatomic site",
#         "A right ventricular (RV)",
#         "icare:icv2000000010",
#         2000000010,
#         "A right ventricular (RV)",
#         "icare:icv2000000010",
#         2000000010,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "A_RV_b",
#         "Right ventricular A (RV)",
#         "anatomic site",
#         "A right ventricular (RV)",
#         "icare:icv2000000010",
#         2000000010,
#         "A right ventricular (RV)",
#         "icare:icv2000000010",
#         2000000010,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "A_septal_a",
#         "A septal",
#         "anatomic site",
#         "A septal",
#         "icare:icv2000000011",
#         2000000011,
#         "A septal",
#         "icare:icv2000000011",
#         2000000011,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "A_septal_b",
#         "Septal A",
#         "anatomic site",
#         "A septal",
#         "icare:icv2000000011",
#         2000000011,
#         "A septal",
#         "icare:icv2000000011",
#         2000000011,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "E_RV_a",
#         "E right ventricular (RV)",
#         "anatomic site",
#         "E right ventricular (RV)",
#         "icare:icv2000000012",
#         2000000012,
#         "E right ventricular (RV)",
#         "icare:icv2000000012",
#         2000000012,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "E_RV_b",
#         "Right ventricular E (RV)",
#         "anatomic site",
#         "E right ventricular (RV)",
#         "icare:icv2000000012",
#         2000000012,
#         "E right ventricular (RV)",
#         "icare:icv2000000012",
#         2000000012,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "E_septal_a",
#         "E septal",
#         "anatomic site",
#         "E septal",
#         "icare:icv2000000013",
#         2000000013,
#         "E septal",
#         "icare:icv2000000013",
#         2000000013,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "E_septal_b",
#         "Septal E",
#         "anatomic site",
#         "E septal",
#         "icare:icv2000000013",
#         2000000013,
#         "E septal",
#         "icare:icv2000000013",
#         2000000013,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "systolic_septal_a",
#         "systolic septal",
#         "anatomic site",
#         "systolic septal",
#         "icare:icv2000000014",
#         2000000014,
#         "systolic septal",
#         "icare:icv2000000014",
#         2000000014,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "systolic_septal_b",
#         "Septal systolic",
#         "anatomic site",
#         "systolic septal",
#         "icare:icv2000000014",
#         2000000014,
#         "systolic septal",
#         "icare:icv2000000014",
#         2000000014,
#         "has anatomic context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "end_study_fu_1",
#         "end of the study follow-up visit",
#         "visit",
#         "end of protocol",
#         "snomed:255253007",
#         4116370,
#         "follow-up visit",
#         "snomed:185389009",
#         4089050,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "end_study_fu_2",
#         "follow up at the end of study",
#         "visit",
#         "end of protocol",
#         "snomed:255253007",
#         4116370,
#         "follow-up visit",
#         "snomed:185389009",
#         4089050,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
#     [
#         "end_study_fu_2",
#         "at end of study",
#         "visit",
#         "end of protocol",
#         "snomed:255253007",
#         4116370,
#         "follow-up visit",
#         "snomed:185389009",
#         4089050,
#         "has temporal context",
#         "",
#         "",
#         "",
#         "",
#         "",
#         "",
#     ],
# ]

# # Write the data to a CSV file
# # csv_filename = "/workspace/mapping_tool/data/eval_datasets/mapped_cohorts/GISSI-HF/custom_codes.csv"
# # with open(csv_filename, "w", newline="") as csvfile:
# #     csvwriter = csv.writer(csvfile, delimiter=",")
# #     csvwriter.writerows(data)
